name: bismark-methyldackel-sra
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - snakemake
    - bismark
    - methyldackel
    - trim-galore
    - sambamba
    - ldc=1.11.0
    - parallel-fastq-dump
    - pysradb
